# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd8c7f669933900b05f2c9d31647fb4609cf9ad9a8b6d72a42afdb9062df2d71bff6f5e86183d7be13b3ba30091dd06b8b17b7779f452b8d496c33d5020da7a

test:
  secret_key_base: d404be599f99bb662fed99561fad6e6d6fe01da3a13257933d7ba98acaa55278daa6e9cc763460224a817108fc9af271a480a95161ba158043cd26a4bfda0c37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
